[package]
name = "kwui-sys"
version = "0.1.0"
edition = "2021"
links = "kwui_static"

[lib]
name = "kwui_sys"
path = "src/lib.rs"

[dependencies]

[build-dependencies]
bindgen = "0.69.4"
cmake = "0.1.50"
