[package]
name = "kwui"
version = "0.1.0"
edition = "2021"

[lib]
name = "kwui"
path = "src/lib.rs"

[dependencies]
log = "0.4.20"

[dependencies.kwui-sys]
path = "kwui-sys"

[[example]]
name = "tour"

[dev-dependencies]
windows_dpi = "0.3.0"
